name: Send TAR file via SendGrid

on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      - main

jobs:
  send-tar:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Generate .tar file
      - name: Generate .tar file
        run: |
          mkdir -p output
          echo "Sample file content" > output/sample.txt
          tar -cvf report.tar output/

      # Step 3: Send .tar file via SendGrid API
      - name: Send .tar file via SendGrid API
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: rushikeshnarala02@gmail.com
          FROM_EMAIL: noreply@si6.io
        run: |
          # Encode TAR file as base64 (single-line to avoid JSON issues)
          base64 -w 0 report.tar > encoded.txt
          ENCODED_CONTENT=$(cat encoded.txt)

          # Create JSON payload
          cat <<EOF > payload.json
          {
            "personalizations": [
              {
                "to": [{ "email": "${TO_EMAIL}" }],
                "subject": "Automated TAR File from GitHub Actions"
              }
            ],
            "from": { "email": "${FROM_EMAIL}" },
            "content": [
              {
                "type": "text/plain",
                "value": "Hello,\n\nPlease find attached the generated TAR file.\n\nRegards,\nGitHub Actions"
              }
            ],
            "attachments": [
              {
                "content": "${ENCODED_CONTENT}",
                "type": "application/x-tar",
                "filename": "report.tar"
              }
            ]
          }
          EOF

          # Send email using SendGrid API and show response
          echo "Sending email via SendGrid..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${SENDGRID_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @payload.json)

          echo "HTTP Response Code: $RESPONSE"
          echo "SendGrid Response:"
          cat response.txt
