name: Send TAR file via SendGrid

on:
  workflow_dispatch:  # manual trigger (you can replace with push/schedule)
  push:
    branches:
      - main
      
jobs:
  send-tar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate .tar file
        run: |
          mkdir output
          echo "Sample file content" > output/sample.txt
          tar -cvf report.tar output/

      - name: Send .tar file via SendGrid API
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: rushikesh@si6.io
          FROM_EMAIL: noreply@si6.io
        run: |
          # Encode TAR file as base64
          base64 report.tar > encoded.txt
          ENCODED_CONTENT=$(cat encoded.txt)

          # Create JSON payload
          cat <<EOF > payload.json
          {
            "personalizations": [
              {
                "to": [{ "email": "${TO_EMAIL}" }],
                "subject": "Automated TAR File from GitHub Actions"
              }
            ],
            "from": { "email": "${FROM_EMAIL}" },
            "content": [
              {
                "type": "text/plain",
                "value": "Hello,\n\nPlease find attached the generated TAR file.\n\nRegards,\nGitHub Actions"
              }
            ],
            "attachments": [
              {
                "content": "${ENCODED_CONTENT}",
                "type": "application/x-tar",
                "filename": "report.tar"
              }
            ]
          }
          EOF

          # Send email using SendGrid API
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${SENDGRID_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @payload.json
